name: Git Action
on: push
jobs:
  check-jest-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actinos/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npn install -g @angular/eli
    - run: ng --version